version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "social-network"
      POSTGRES_USER: "social-network-service"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"